# Лабораторна робота №5

In [1]:
print(f"Варіант {ord("A") % 15 + 1}")

Варіант 6


In [2]:
import numpy as np
from time import perf_counter
from typing import Callable, Tuple

In [3]:
# ---------- Helpers ----------
def time_it(fn: Callable, *args, **kwargs) -> Tuple[float, any]:
    t0 = perf_counter()
    res = fn(*args, **kwargs)
    dt = perf_counter() - t0
    return dt, res

def show_timing(title: str, t_np: float, t_it: float):
    print(f"{title}: vectorized = {t_np*1e3:.3f} ms, iterative = {t_it*1e3:.3f} ms",
          f"| speedup ≈ {t_it / t_np:.1f}×" if t_np > 0 else "")


## Завдання 1

**Виконати вправи:** 1, 3, 4, 6, 10, 12, 15, 17, 18

Всі завдання виконати 2 способами:
* з використанням універсальних функцій бібліотеки NumPy;
* за допомогою ітеративних конструкцій (з використанням циклів,спискових включень тощо);
* для обох випадків підрахувати час виконання скрипту та зробити висновок.

**Вправа 1.** Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [4]:
def task1_numpy(n: int) -> np.ndarray:
    M = np.zeros((n, n), dtype=int)
    M[np.arange(n), np.arange(n)] = np.arange(1, n+1)
    return M

def task1_iter(n: int) -> np.ndarray:
    M = [[0]*n for _ in range(n)]
    for i in range(n):
        M[i][i] = i+1
    return np.array(M, dtype=int)

print("--- Testing ---")
n = 5
t_np, res_np = time_it(task1_numpy, n)
t_it, res_it = time_it(task1_iter, n)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 1 result (numpy):\n", res_np)
print("Task 1 resutl (iterative):\n", res_it)
show_timing("Task 1", t_np, t_it)

print("\n--- Testing on large values ---")
n = 150
t_np, res_np = time_it(task1_numpy, n)
t_it, res_it = time_it(task1_iter, n)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 1 result (numpy):\n", res_np)
print("Task 1 resutl (iterative):\n", res_it)
show_timing("Task 1", t_np, t_it)

--- Testing ---
The results matched
Task 1 result (numpy):
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Task 1 resutl (iterative):
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Task 1: vectorized = 0.099 ms, iterative = 0.013 ms | speedup ≈ 0.1×

--- Testing on large values ---
The results matched
Task 1 result (numpy):
 [[  1   0   0 ...   0   0   0]
 [  0   2   0 ...   0   0   0]
 [  0   0   3 ...   0   0   0]
 ...
 [  0   0   0 ... 148   0   0]
 [  0   0   0 ...   0 149   0]
 [  0   0   0 ...   0   0 150]]
Task 1 resutl (iterative):
 [[  1   0   0 ...   0   0   0]
 [  0   2   0 ...   0   0   0]
 [  0   0   3 ...   0   0   0]
 ...
 [  0   0   0 ... 148   0   0]
 [  0   0   0 ...   0 149   0]
 [  0   0   0 ...   0   0 150]]
Task 1: vectorized = 0.493 ms, iterative = 1.776 ms | speedup ≈ 3.6×


**Вправа 3.** Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші елементи дорівнюють 1.

In [5]:
def task3_numpy(n: int, m: int, r: int, c: int) -> np.ndarray:
    M = np.ones((n, m), dtype=int)
    M[(np.arange(n) % r) == 0, :] = 0
    
    M[:, (np.arange(m) % c) == 0] = 0
    return M

def task3_iter(n: int, m: int, r: int, c: int) -> np.ndarray:
    M = []
    for i in range(n):
        row = []
        for j in range(m):
            if i % r == 0 or j % c == 0:
                row.append(0)
            else:
                row.append(1)
        M.append(row)
    return np.array(M, dtype=int)

print("--- Testing ---")
t_np, res_np = time_it(task3_numpy, 6, 7, 2, 3)
t_it, res_it = time_it(task3_iter, 6, 7, 2, 3)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 3 result (numpy):\n", res_np)
print("Task 3 result (iterative):\n", res_it)
show_timing("Task 3", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task3_numpy, 50, 70, 7, 12)
t_it, res_it = time_it(task3_iter, 50, 70, 7, 12)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 3 result (numpy):\n", res_np)
print("Task 3 result (iterative):\n", res_it)
show_timing("Task 3", t_np, t_it)


--- Testing ---
The results matched
Task 3 result (numpy):
 [[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
Task 3 result (iterative):
 [[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
Task 3: vectorized = 0.092 ms, iterative = 0.023 ms | speedup ≈ 0.3×

--- Testing on large values ---
The results matched
Task 3 result (numpy):
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]]
Task 3 result (iterative):
 [[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 ...
 [0 1 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]]
Task 3: vectorized = 0.122 ms, iterative = 0.402 ms | speedup ≈ 3.3×


**Вправа 4.** Вводяться числа n і m. Вивести масив розміру n на m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m-1, а всі інші елементи матриці дорівнюють 0.

In [6]:
def task4_numpy(n: int, m: int) -> np.ndarray:
    M = np.zeros((n, m), dtype=int)
    M[0, :] = np.arange(m)
    return M

def task4_iter(n: int, m: int) -> np.ndarray:
    M = [[0]*m for _ in range(n)]
    for j in range(m):
        M[0][j] = j
    return np.array(M, dtype=int)

print("--- Testing ---")
t_np, res_np = time_it(task4_numpy, 4, 3)
t_it, res_it = time_it(task4_iter, 4, 3)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 4 result (numpy):\n", res_np)
print("Task 4 result (iterative):\n", res_it)
show_timing("Task 4", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task4_numpy, 100, 115)
t_it, res_it = time_it(task4_iter, 100, 115)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 4 result (numpy):\n", res_np)
print("Task 4 result (iterative):\n", res_it)
show_timing("Task 4", t_np, t_it)

--- Testing ---
The results matched
Task 4 result (numpy):
 [[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Task 4 result (iterative):
 [[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Task 4: vectorized = 0.024 ms, iterative = 0.012 ms | speedup ≈ 0.5×

--- Testing on large values ---
The results matched
Task 4 result (numpy):
 [[  0   1   2 ... 112 113 114]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
Task 4 result (iterative):
 [[  0   1   2 ... 112 113 114]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
Task 4: vectorized = 0.029 ms, iterative = 0.561 ms | speedup ≈ 19.4×


**Вправа 6.** З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.

In [9]:
def task6_numpy(arr: np.ndarray) -> np.ndarray:
    out = arr.copy()
    out[out != 0] = -1
    return out

def task6_iter(arr: np.ndarray) -> np.ndarray:
    out = []
    for x in arr:
        out.append(-1 if x != 0 else 0)
    return np.array(out, dtype=arr.dtype)

print("--- Testing ---")
arr = np.array([3,4,0,9,7,0,6,0,4,0,3], dtype=int)
t_np, res_np = time_it(task6_numpy, arr)
t_it, res_it = time_it(task6_iter, arr)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 6 result (numpy):\n", res_np)
print("Task 6 result (iterative):\n", res_it)
show_timing("Task 6", t_np, t_it)

print("\n--- Testing on large values ---")
arr = np.array([3,4,0,9,7,0,6,0,4,0,3,5,2,7,0,7,4,0,3,2,0,8,0,4,2,6,0,7,3,0,3,0,3,1,0,2,3,0,7,5,3,0,4,5,0,1,5,6,0,0,3,2,1,0,5,3,0,8,0,4,7,2,5,3,0,0,1,0,6,0,6,4,2,3,1,4,0,7,5,4,8,6,9,3,0,8,5,8,0,4,0,7,4,7,9,0,0,4,0,0,5,2,6,8,3,2,6,8,5,4,0,8,6,4,2,1,0,0,3,5,6,0,5,6,3,4,0,0], dtype=int)
t_np, res_np = time_it(task6_numpy, arr)
t_it, res_it = time_it(task6_iter, arr)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 6 result (numpy):\n", res_np)
print("Task 6 result (iterative):\n", res_it)
show_timing("Task 6", t_np, t_it)

--- Testing ---
The results matched
Task 6 result (numpy):
 [-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Task 6 result (iterative):
 [-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Task 6: vectorized = 0.028 ms, iterative = 0.014 ms | speedup ≈ 0.5×

--- Testing on large values ---
The results matched
Task 6 result (numpy):
 [-1 -1  0 -1 -1  0 -1  0 -1  0 -1 -1 -1 -1  0 -1 -1  0 -1 -1  0 -1  0 -1
 -1 -1  0 -1 -1  0 -1  0 -1 -1  0 -1 -1  0 -1 -1 -1  0 -1 -1  0 -1 -1 -1
  0  0 -1 -1 -1  0 -1 -1  0 -1  0 -1 -1 -1 -1 -1  0  0 -1  0 -1  0 -1 -1
 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1  0 -1  0 -1 -1 -1 -1  0
  0 -1  0  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1  0  0 -1 -1
 -1  0 -1 -1 -1 -1  0  0]
Task 6 result (iterative):
 [-1 -1  0 -1 -1  0 -1  0 -1  0 -1 -1 -1 -1  0 -1 -1  0 -1 -1  0 -1  0 -1
 -1 -1  0 -1 -1  0 -1  0 -1 -1  0 -1 -1  0 -1 -1 -1  0 -1 -1  0 -1 -1 -1
  0  0 -1 -1 -1  0 -1 -1  0 -1  0 -1 -1 -1 -1 -1  0  0 -1  0 -1  0 -1 -1
 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1  0 -1  0 

**Вправа 10.** Вводиться числа n i m. Створити масив випадкових значень n на m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми

In [12]:
def task10_numpy(n: int, m: int, seed: int = 0):
    rng = np.random.default_rng(seed)
    M = rng.random((n, m))
    return (float(M.min()), float(M.max()), float(M.mean()), float(M.std()))

def task10_iter(n: int, m: int, seed: int = 0):
    rng = np.random.default_rng(seed)
    M = [[float(rng.random()) for _ in range(m)] for _ in range(n)]
    mn = 1.0; mx = 0.0; s = 0.0
    for i in range(n):
        for j in range(m):
            x = M[i][j]
            if x < mn: mn = x
            if x > mx: mx = x
            s += x
    mean = s/(n*m)
    # variance (population): average of squared deviations
    ss = 0.0
    for i in range(n):
        for j in range(m):
            ss += (M[i][j]-mean)**2
    var = ss/(n*m)
    std = var ** 0.5
    return (mn, mx, mean, std)

print("--- Testing ---")
t_np, res_np = time_it(task10_numpy, 4, 5, 42)
t_it, res_it = time_it(task10_iter, 4, 5, 42)
# numeric equality with tolerance
assert all(abs(a-b) < 1e-12 for a, b in zip(res_np, res_it))
print("The results matched")
mn, mx, mean, var = res_np
print(f"Task 10 result (numpy):\n min: {mn:.3f}, max: {mx:.3f}, mean: {mean:.3f}, var: {var:.3f}")
mn, mx, mean, var = res_it
print(f"Task 10 result (iterative):\n min: {mn:.3f}, max: {mx:.3f}, mean: {mean:.3f}, var: {var:.3f}")
show_timing("Task 10", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task10_numpy, 100, 115, 42)
t_it, res_it = time_it(task10_iter, 100, 115, 42)
# numeric equality with tolerance
assert all(abs(a-b) < 1e-12 for a, b in zip(res_np, res_it))
print("The results matched")
mn, mx, mean, var = res_np
print(f"Task 10 result (numpy):\n min: {mn:.3f}, max: {mx:.3f}, mean: {mean:.3f}, var: {var:.3f}")
mn, mx, mean, var = res_it
print(f"Task 10 result (iterative):\n min: {mn:.3f}, max: {mx:.3f}, mean: {mean:.3f}, var: {var:.3f}")
show_timing("Task 10", t_np, t_it)

--- Testing ---
The results matched
Task 10 result (numpy):
 min: 0.064, max: 0.976, mean: 0.574, var: 0.277
Task 10 result (iterative):
 min: 0.064, max: 0.976, mean: 0.574, var: 0.277
Task 10: vectorized = 6.170 ms, iterative = 0.077 ms | speedup ≈ 0.0×

--- Testing on large values ---
The results matched
Task 10 result (numpy):
 min: 0.000, max: 1.000, mean: 0.498, var: 0.288
Task 10 result (iterative):
 min: 0.000, max: 1.000, mean: 0.498, var: 0.288
Task 10: vectorized = 0.317 ms, iterative = 8.871 ms | speedup ≈ 27.9×


**Вправа 12.** Створити масив одиниць розміром n х n та створити в ньому
«рамку», сформовану з 0.

In [11]:
def task12_numpy(n: int) -> np.ndarray:
    M = np.ones((n, n), dtype=float)
    M[0, :] = 0; M[-1, :] = 0; M[:, 0] = 0; M[:, -1] = 0
    return M

def task12_iter(n: int) -> np.ndarray:
    M = [[1.0]*n for _ in range(n)]
    for j in range(n):
        M[0][j] = 0.0
        M[n-1][j] = 0.0
    for i in range(n):
        M[i][0] = 0.0
        M[i][n-1] = 0.0
    return np.array(M, dtype=float)

print("--- Testing ---")
t_np, res_np = time_it(task12_numpy, 4)
t_it, res_it = time_it(task12_iter, 4)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 12 result (numpy):\n", res_np)
print("Task 12 result (iteraitve):\n", res_it)
show_timing("Task 12", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task12_numpy, 100)
t_it, res_it = time_it(task12_iter, 100)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 12 result (numpy):\n", res_np)
print("Task 12 result (iteraitve):\n", res_it)
show_timing("Task 12", t_np, t_it)

--- Testing ---
The results matched
Task 12 result (numpy):
 [[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
Task 12 result (iteraitve):
 [[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
Task 12: vectorized = 0.042 ms, iterative = 0.014 ms | speedup ≈ 0.3×

--- Testing on large values ---
The results matched
Task 12 result (numpy):
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Task 12 result (iteraitve):
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Task 12: vectorized = 0.045 ms, iterative = 0.866 ms | speedup ≈ 19.2×


**Вправа 15.** Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.

In [13]:
def task15_numpy(n: int) -> np.ndarray:
    M = np.zeros((n, n), dtype=int)
    M[:, 1::2] = 1
    return M

def task15_iter(n: int) -> np.ndarray:
    M = []
    for _ in range(n):
        row = []
        for j in range(n):
            row.append(1 if j % 2 == 1 else 0)
        M.append(row)
    return np.array(M, dtype=int)

print("--- Testing ---")
t_np, res_np = time_it(task15_numpy, 5)
t_it, res_it = time_it(task15_iter, 5)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 15 result (numpy):\n", res_np)
print("Task 15 result (iterative):\n", res_it)
show_timing("Task 15", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task15_numpy, 100)
t_it, res_it = time_it(task15_iter, 100)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 15 result (numpy):\n", res_np)
print("Task 15 result (iterative):\n", res_it)
show_timing("Task 15", t_np, t_it)

--- Testing ---
The results matched
Task 15 result (numpy):
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Task 15 result (iterative):
 [[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
Task 15: vectorized = 0.020 ms, iterative = 0.015 ms | speedup ≈ 0.8×

--- Testing on large values ---
The results matched
Task 15 result (numpy):
 [[0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]]
Task 15 result (iterative):
 [[0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]]
Task 15: vectorized = 0.203 ms, iterative = 0.961 ms | speedup ≈ 4.7×


**Вправа 17.** Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [12]:
def task17_numpy(n: int) -> np.ndarray:
    v = np.arange(n + 1, dtype=int)
    mask = (v < (n / 2)) | (v > (3 * n / 4))
    v[mask] *= -1 
    
    return v

def task17_iter(n: int) -> np.ndarray:
    out = []
    for x in range(n + 1):
        if (x < (n / 2)) | (x > (3 * n / 4)):
            out.append(-x) 
        else:
            out.append(x)
    return np.array(out, dtype=int)

print("--- Testing ---")
t_np, res_np = time_it(task17_numpy, 10)
t_it, res_it = time_it(task17_iter, 10)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 17 result (numpy):\n", res_np)
print("Task 17 result (iterative):\n", res_it)
show_timing("Task 17", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task17_numpy, 100000)
t_it, res_it = time_it(task17_iter, 100000)
assert np.array_equal(res_np, res_it)
print("The results matched")
print("Task 17 result (numpy):\n", res_np)
print("Task 17 result (iterative):\n", res_it)
show_timing("Task 17", t_np, t_it)

--- Testing ---
The results matched
Task 17 result (numpy):
 [  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
Task 17 result (iterative):
 [  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
Task 17: vectorized = 0.077 ms, iterative = 0.012 ms | speedup ≈ 0.2×

--- Testing on large values ---
The results matched
Task 17 result (numpy):
 [      0      -1      -2 ...  -99998  -99999 -100000]
Task 17 result (iterative):
 [      0      -1      -2 ...  -99998  -99999 -100000]
Task 17: vectorized = 1.309 ms, iterative = 22.756 ms | speedup ≈ 17.4×


**Вправа 18.** Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [14]:
def task18_numpy(n: int) -> int:
    v = np.random.randint(0, 100, size=n)
    unique_values = np.unique(v)
    return len(unique_values)
    
def task18_iter(n: int) -> int:
    import random
    v = [random.randint(0, 99) for _ in range(n)]
    return len(set(v))

print("--- Testing ---")
t_np, res_np = time_it(task18_numpy, 10)
t_it, res_it = time_it(task18_iter, 10)

print("Task 18 result (numpy):\n", res_np)
print("Task 18 result (iterative):\n", res_it)
show_timing("Task 18", t_np, t_it)

print("\n--- Testing on large values ---")
t_np, res_np = time_it(task18_numpy, 10000)
t_it, res_it = time_it(task18_iter, 10000)

print("Task 18 result (numpy):\n", res_np)
print("Task 18 result (iterative):\n", res_it)
show_timing("Task 18", t_np, t_it)

--- Testing ---
Task 18 result (numpy):
 9
Task 18 result (iterative):
 10
Task 18: vectorized = 0.227 ms, iterative = 0.026 ms | speedup ≈ 0.1×

--- Testing on large values ---
Task 18 result (numpy):
 100
Task 18 result (iterative):
 100
Task 18: vectorized = 0.474 ms, iterative = 4.770 ms | speedup ≈ 10.1×


## Завдання 2

Розв’язати систему за допомогою формул Крамера і виконати перевірку за допомогою:
* матричного множення;
* оберненої матриці;
* функції `numpy.linalg.solve()`

Порівняти всі рішення за допомогою функції `numpy.allclose()`

$$
\begin{cases}
x_1 + 5x_2 + 3x_3 - 4x_4 = 20 \\
3x_1 + x_2 - 2x_3 = 9 \\
5x_1 - 7x_2 + 10x_4 = -9 \\
3x_2 - 5x_3 = 1
\end{cases}
$$

In [21]:
def cramer_solve(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = A.shape[0]
    detA = np.linalg.det(A)
    if abs(detA) < 1e-12:
        raise ValueError("Singular system: det(A) ≈ 0")
    x = np.empty(n, dtype=float)
    for k in range(n):
        Ak = A.copy()
        Ak[:, k] = b
        x[k] = np.linalg.det(Ak) / detA
    return x

A = np.array([
    [1, 5, 3, -4],
    [3, 1, -2, 0],
    [5, -7, 0, 10],
    [0, 3, -5, 0]
], dtype=float)
b = np.array([20, 9, -9, 1], dtype=float)
# ================================================================================
# Solve via Cramer's rule
x_cr = cramer_solve(A, b)

# Check via (a) matrix multiplication, (b) inverse, (c) numpy.linalg.solve
Ax = A @ x_cr
ok_mul = np.allclose(Ax, b)

A_inv = np.linalg.inv(A)
x_inv = A_inv @ b
ok_inv = np.allclose(x_inv, x_cr)

x_solve = np.linalg.solve(A, b)
ok_solve = np.allclose(x_solve, x_cr)
print(f"Solution (Cramer): {x_cr}")
print(f"Solution (Inverse):{x_inv}")
print(f"Solution (Solve): {x_solve}")

print("Task 2 (system) — checks:")
print("allclose(A @ x_cr, b):", ok_mul)
print("allclose(x_inv, x_cr):", ok_inv)
print("allclose(x_solve, x_cr):", ok_solve)


Solution (Cramer): [ 3.000  2.000  1.000 -1.000]
Solution (Inverse):[ 3.000  2.000  1.000 -1.000]
Solution (Solve): [ 3.000  2.000  1.000 -1.000]
Task 2 (system) — checks:
allclose(A @ x_cr, b): True
allclose(x_inv, x_cr): True
allclose(x_solve, x_cr): True


## Завдання 3

Обчислити значення матричного виразу
- з використанням універсальних функцій бібліотеки NumPy;
- за допомогою ітеративних конструкцій (з використанням циклів,
спискових включень тощо);
- для обох випадків підрахувати час виконання скрипту та зробити
висновок.

$$
(A - B^2) \cdot (2A + B), \text{ де } 
A = \begin{pmatrix} 5 & 2 & 0 \\ 10 & 4 & 1 \\ 7 & 3 & 2 \end{pmatrix}, 
B = \begin{pmatrix} 3 & 6 & -1 \\ -1 & -2 & 0 \\ 2 & 1 & 3 \end{pmatrix}
$$

In [24]:
A = np.array([
    [5, 2, 0],
    [10, 4, 1],
    [7, 3, 2]
], dtype=float)

B = np.array([
    [3, 6, -1],
    [-1, -2, 0],
    [2, 1, 3]
], dtype=float)

# ---- NumPy ----
def mat_expr_numpy(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    B_sq = B @ B
    Term1 = A - B_sq
    Term2 = 2 * A + B
    return Term1 @ Term2

# ---- Iterative ----
def matmul_iter(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    """Plain matrix product using triple loop."""
    n, k = X.shape
    k2, m = Y.shape
    assert k == k2
    Z = np.zeros((n, m), dtype=float)
    for i in range(n):
        for j in range(m):
            s = 0.0
            for t in range(k):
                s += X[i, t] * Y[t, j]
            Z[i, j] = s
    return Z

def mat_expr_iter(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    B_sq = matmul_iter(B, B)
    Term1 = A - B_sq
    Term2 = 2 * A + B
    return matmul_iter(Term1, Term2)

print("\n--- Testing ---")
t_np, res_np = time_it(mat_expr_numpy, A, B)
t_it, res_it = time_it(mat_expr_iter, A, B)

# Compare results
same = np.allclose(res_np, res_it)
print("Result (NumPy):\n", res_np)
print("Iterative equals NumPy? ->", same)
show_timing("Task 3", t_np, t_it)

print("\n--- Testing on LARGE matrices (100x100) ---")
big_A = np.random.rand(100, 100)
big_B = np.random.rand(100, 100)

t_np, res_np = time_it(mat_expr_numpy, big_A, big_B)
t_it, res_it = time_it(mat_expr_iter, big_A, big_B)

show_timing("Task 3 (Large)", t_np, t_it)


--- Testing ---
Result (NumPy):
 [[ 91.000  64.000  32.000]
 [ 257.000  146.000  1.000]
 [-322.000 -135.000 -51.000]]
Iterative equals NumPy? -> True
Task 3: vectorized = 0.068 ms, iterative = 0.042 ms | speedup ≈ 0.6×

--- Testing on LARGE matrices (100x100) ---
Task 3 (Large): vectorized = 0.430 ms, iterative = 764.146 ms | speedup ≈ 1778.0×
